product views파일 수정
wecode-bootcamp-korea/14-1st-StyleCode-backend pull request #10
Opened 2020-11-24 07:57 UTC by cs982607

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
git clone 후 새로운 branch로 push
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-24 09:18 UTC, ulfrid requested changes

2020-11-24 09:18 UTC, ulfrid commented on product/views.py
> +            print (first_categories)
print는 제거해주세요!

2020-11-24 09:18 UTC, ulfrid commented on product/views.py
> +            return JsonResponse({ 'message:':'SUCCESS', 'categories':categories}, status=200)
```suggestion
            return JsonResponse({'categories':categories}, status=200)
```
성공했다면 성공메세지는 따로 주지않아도 괜찮습니다.

2020-11-24 09:18 UTC, ulfrid commented on product/views.py
> +                return JsonResponse({'message:':'SUCCESS', 'third_category_list':third_category_list, 'sorting':sorting}, status=200)
위의 Q처리에서 이미 카테고리의 여부를 확인했기때문에 뿌려주는 로직은 이렇게 일일히 하는게 아니라 products 결과 한번만 뿌려주면 카테고리에 따라 뿌려지게 됩니다. 내용도 같죠! 한번만 뿌려주세요.  
```suggestion
                return JsonResponse({'data' : product_list, 'sorting':sorting}, status=200)
```

2020-11-24 15:02 UTC, cs982607 commented on product/views.py
> +            print (first_categories)
수정하였습니다

2020-11-24 15:02 UTC, cs982607 commented on product/views.py
> +            return JsonResponse({ 'message:':'SUCCESS', 'categories':categories}, status=200)
수정하였습니다

2020-11-25 04:39 UTC, cs982607 commented on product/views.py
> +                return JsonResponse({'message:':'SUCCESS', 'third_category_list':third_category_list, 'sorting':sorting}, status=200)
수정하였습니다

2020-11-26 06:26 UTC, ulfrid commented
LGTM.

2020-11-26 06:26 UTC, merged