Feature/user
wecode-bootcamp-korea/14-1st-StyleCode-backend pull request #5
Opened 2020-11-20 10:03 UTC by cs982607

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
로그인, 회원가입 구현 후 테스트		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-23 06:46 UTC, ulfrid requested changes
전체적인 코드 상태가 실제 실행없이 PUSH하신것 같네요. 확인 부탁드립니다.

2020-11-23 06:46 UTC, devops-andrew commented on user/views.py
> +                return jsonresponse ({'message':'invalid_id'}, status=400)
```suggestion
                return JsonResponse ({'message':'iINVALID_USER'}, status=400)
```

2020-11-23 06:46 UTC, devops-andrew commented on user/views.py
> +                return jsonresponse ({'message:':'invalid_email'}, status=400)
```suggestion
                return JsonResponse ({'message:':'INVALID_EMAIL'}, status=400)
```

2020-11-23 06:46 UTC, devops-andrew commented on user/views.py
> +                return jsonresponse ({'message:':'invalid_password'}, status=400)
```suggestion
                return JsonResponse ({'message:':'INVALID_PASSWORD'}, status=400)
```

2020-11-23 06:46 UTC, devops-andrew commented on user/views.py
> +                return jsonresponse ({'message:':'already_email'}, status=400)
```suggestion
                return JsonResponse ({'message:':'EXIST_EMAIL'}, status=400)
```

2020-11-23 06:46 UTC, devops-andrew commented on user/views.py
> +                return jsonresponse ({'message':'already_nickname'}, status=400)
```suggestion
                return JsonResponse ({'message':'EXIST_NICKNAME'}, status=400)
```

2020-11-23 06:46 UTC, devops-andrew commented on user/views.py
> +            return jsonresponse ({'message:':'create_user'}, status=200)
```suggestion
            return JsonResponse ({'message:':'SUCCESS'}, status=200)
```

2020-11-23 06:46 UTC, devops-andrew commented on user/views.py
> +        except keyerror:
```suggestion
        except KeyError:
```

2020-11-23 06:46 UTC, devops-andrew commented on user/views.py
> +            return jsonresponse({'message:':'key_error'}, status=400)
```suggestion
            return JsonResponse({'message:':'INVALID_KEYS'}, status=400)
```

2020-11-23 06:46 UTC, devops-andrew commented on user/views.py
> +                return jsonresponse({'token':token}, status=200)
```suggestion
                return JsonResponse({'token':token}, status=200)
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +            user = user.objects.get(id = request.user_id)
login_decorator 를 통해서 유저를 가져와주세요.

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +            return jsonresponse({'message:':'invalid_password'}, status=400)
```suggestion
            return JsonResponse({'message:':'INVALID_PASSWORD'}, status=400)
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +        except keyerror:
```suggestion
        except KeyError:
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +            return jsonresponse({'message:':'invalid_id'}, status=400)
```suggestion
            return JsonResponse({'message:':'INVALID_KEYS'}, status=400)
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +        except user.doesnotexist:
```suggestion
        except User.DoesNotExist:
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +            return jsonresponse({'message:':'user_does_not_exist'}, status=400)
```suggestion
            return jsonresponse({'message:':'INVALID_USER'}, status=400)
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +            return jsonresponse ({'user_info:': user_info}, status=400)
```suggestion
            return JsonResponse ({'user_info:': user_info}, status=200)
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +        except keyerror:
```suggestion
        except KeyError:
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +            return jsonresponse({'message:':'key_error'}, status=400)
```suggestion
            return JsonResponse({'message:':'INVALID_KEYS'}, status=400)
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +            user = user.objects.get(id = request.user_id)
user는 데코레이터 통해서 가져오고 있으므로, 다시 가져올 필요 없습니다.
```suggestion
            user = request.user
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +            return jsonresponse({'message:':'success'}, status=200)
```suggestion
            return JsonResponse({'message:':'SUCCESS'}, status=200)
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +        except keyerror:
```suggestion
        except KeyError:
```

2020-11-23 06:46 UTC, ulfrid commented on user/views.py
> +            return jsonresponse({'message:':'key_error'}, status=400)
```suggestion
            return JsonResponse({'message:':'INVALID_KEYS'}, status=400)
```

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message':'invalid_id'}, status=400)
수정하였습니다

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message:':'invalid_email'}, status=400)
수정하였습니다

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'key_error'}, status=400)
수정하였습니다

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +        except keyerror:
수정하였습니다

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'success'}, status=200)
수정하였습니다

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +            user = user.objects.get(id = request.user_id)
수정하였습니다

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'key_error'}, status=400)
수정하였습니다

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message':'already_nickname'}, status=400)
수정하였습니다

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +            return jsonresponse ({'message:':'create_user'}, status=200)
수정하였습니다

2020-11-23 09:00 UTC, cs982607 commented on user/views.py
> +        except keyerror:
수정하였습니다

2020-11-23 09:01 UTC, cs982607 commented on user/views.py
> +                return jsonresponse({'token':token}, status=200)
수정하였습니다

2020-11-23 09:01 UTC, cs982607 commented on user/views.py
> +            user = user.objects.get(id = request.user_id)
수정하였습니다

2020-11-23 09:01 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'invalid_password'}, status=400)
수정하였습니다

2020-11-23 09:01 UTC, cs982607 commented on user/views.py
> +        except keyerror:
수정하였습니다

2020-11-23 09:01 UTC, cs982607 commented on user/views.py
> +        except user.doesnotexist:
수정하였습니다

2020-11-23 09:01 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'user_does_not_exist'}, status=400)
수정하였습니다

2020-11-23 09:02 UTC, cs982607 commented on user/views.py
> +            return jsonresponse ({'user_info:': user_info}, status=400)
수정하였습니다

2020-11-23 09:02 UTC, cs982607 commented on user/views.py
> +        except keyerror:
수정하였습니다

2020-11-23 09:02 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'key_error'}, status=400)
수정하였습니다

2020-11-23 09:06 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message:':'invalid_password'}, status=400)
수정하였습니다

2020-11-23 09:07 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message:':'already_email'}, status=400)
수정하였습니다

2020-11-23 09:08 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'key_error'}, status=400)
수정하였습니다

2020-11-23 09:09 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'key_error'}, status=400)
수정하였습니다

2020-11-23 09:09 UTC, cs982607 commented on user/views.py
> +        except keyerror:
수정하였습니다

2020-11-23 09:09 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'success'}, status=200)
수정하였습니다

2020-11-23 09:09 UTC, cs982607 commented on user/views.py
> +            user = user.objects.get(id = request.user_id)
수정하였습니다

2020-11-23 09:09 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'key_error'}, status=400)
수정하였습니다

2020-11-23 09:09 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message':'already_nickname'}, status=400)
수정하였습니다

2020-11-23 09:10 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message:':'already_email'}, status=400)
수정하였습니다

2020-11-23 09:10 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message:':'invalid_password'}, status=400)
수정하였습니다

2020-11-23 09:10 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message:':'invalid_email'}, status=400)
수정하였습니다

2020-11-23 09:10 UTC, cs982607 commented on user/views.py
> +                return jsonresponse ({'message':'invalid_id'}, status=400)
수정하였습니다

2020-11-23 09:53 UTC, cs982607 commented on user/views.py
> +            return jsonresponse({'message:':'invalid_id'}, status=400)
수정하였습니다

2020-11-24 07:05 UTC, merged

2020-11-24 07:05 UTC, ulfrid commented
LGTM.