Feature/ootd
wecode-bootcamp-korea/14-1st-StyleCode-backend pull request #7
Opened 2020-11-20 12:05 UTC by BaekChan1024

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- ootd 주요 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 디테일 페이지 sns 카드 리스트, 좋아요, 팔로우, 댓글, 대댓글 구현 아직 에러처리 미흡

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-23 14:43 UTC, ulfrid commented
리뷰의 덩어리가 큽니다. 업로더나 csv 파일들은 git에 등록하지마세요. ignore에 등록하고, cache 삭제해주세요. 정리하시면 다시 리뷰 진행하겠습니다.

2020-11-24 06:38 UTC, ulfrid requested changes
확인해보시고 수정 부탁드립니다.

2020-11-24 06:38 UTC, ulfrid commented on ootd/views.py
> +                    OotdTag.objects.create(ootd =post, tag = tag)
```suggestion
                    post.tag.add(tag)
```
연결을 더 잘살려보는건 어떨까요?

2020-11-24 06:38 UTC, ulfrid commented on ootd/views.py
> +                    tag =Tag.objects.create(tag_name=str('#'+tag))
```suggestion
                    tag =Tag.objects.get_or_create(tag_name=str('#'+tag))
```
위의 쿼리셋 메소드를 사용하면 있는것 없는 것 밸리데이션 줄일수 있을것 같네요.

2020-11-24 06:38 UTC, ulfrid commented on ootd/views.py
> +        data = json.loads(request.body)
delete 메소드는 body를 사용하지 않습니다.

2020-11-24 06:38 UTC, ulfrid commented on ootd/views.py
> +        data = json.loads(request.body)
마찬가지입니다.

2020-11-24 06:38 UTC, ulfrid commented on ootd/views.py
> +        data = json.loads(request.body)
여기도 확인해 주세요.

2020-11-24 06:38 UTC, ulfrid commented on ootd/views.py
> +        data = json.loads(request.body)
이부분도요

2020-11-24 06:55 UTC, BaekChan1024 commented on ootd/views.py
> +                    OotdTag.objects.create(ootd =post, tag = tag)
넵 수정하고 QuerySet에 대하여 좀더 공부해 보겠습니다

2020-11-24 06:56 UTC, BaekChan1024 commented on ootd/views.py
> +        data = json.loads(request.body)
아 잉여 변수가 들어갔네요. 삭제 하겠습니다.

2020-11-24 06:57 UTC, BaekChan1024 commented on ootd/views.py
> +                    tag =Tag.objects.create(tag_name=str('#'+tag))
넵 수정 하겠습니다.

2020-11-24 06:57 UTC, BaekChan1024 commented on ootd/views.py
> +        data = json.loads(request.body)
넵 삭제 하겠습니다.

2020-11-24 06:58 UTC, BaekChan1024 commented on ootd/views.py
> +        data = json.loads(request.body)
.... 삭제하겠습니다

2020-11-24 06:58 UTC, BaekChan1024 commented on ootd/views.py
> +        data = json.loads(request.body)
넵!

2020-11-24 09:04 UTC, ulfrid requested changes

2020-11-24 09:04 UTC, ulfrid commented on ootd/views.py
> +                OotdTag.objects.create(ootd =post, tag = tag)
```suggestion
                OotdTag.objects.create(ootd =post, tag = tag)
```
이코드가 남아 있으면 중복생성 될것 같은데 아닌가요? 확인 부탁드립니다.

2020-11-24 09:36 UTC, BaekChan1024 commented on ootd/views.py
> +                OotdTag.objects.create(ootd =post, tag = tag)
중복으로 코드를 짠 것 같습니다... 삭제 하겠습니다!

2020-11-24 10:47 UTC, ulfrid commented
LGTM!

2020-11-24 10:48 UTC, merged